Taste&Sip App
nzlicrbc/TasteSip pull request #1
Opened 2024-08-05 13:06 UTC by nzlicrbc

2024-08-12 11:16 UTC, kerimisoffline requested changes
Eline sağlık

2024-08-12 11:16 UTC, kerimisoffline commented on app/src/main/java/com/example/tastesip/ui/fragment/MealListFragment.kt
> +    private lateinit var viewModel: ListViewModel
```
    private val viewModel: ListViewModel by viewModels(
        factoryProducer = { ListViewModelFactory(MealRepository(RetrofitClient.mealApiService), CocktailRepository(RetrofitClient.cocktailApiService)) }
    )
```
    
  burada da tanımlayabilirim (opsiyonel)

2024-08-12 11:16 UTC, kerimisoffline commented on app/src/main/java/com/example/tastesip/ui/adapter/MealListAdapter.kt
> +        notifyDataSetChanged()
notifyDataSetChanged()'ları kaldıralım. Bir adet DiffUtil classı oluştur. Bu class değişen itemleri analiz ederek gereksiz updatelerden kaçınmayı sağlayacak. Bence bu task kapsamında bu konuya girebiliriz. Araştırmalarını direkt olarak DiffUtil olarak yapabilirsin.

2024-08-12 11:16 UTC, kerimisoffline commented on app/src/main/res/layout/fragment_meal_list.xml
> +    <androidx.recyclerview.widget.RecyclerView
Meal list ile cocktail list arasında bir fark göremedim. Tek xml üzerinden iki fragment'ıda çalıştırsak nasıl olur. Hatta bir adet ListFragment yapalım. Meal ve cocktail fragmentları bundan türesin. 

class MealListFragment: ListFragment() {} gibi bir entegrasyon

2024-08-12 11:16 UTC, kerimisoffline commented on app/src/main/java/com/example/tastesip/ui/adapter/CocktailDetailAdapter.kt
> +sealed class CocktailDetailItem {
Bu classtan dışarı çıkartalım. Harici bir class olsun.

2024-08-12 11:16 UTC, kerimisoffline commented on app/src/main/java/com/example/tastesip/ui/adapter/MealDetailAdapter.kt
> +sealed class MealDetailItem {
Dışarı alalım

2024-08-12 11:16 UTC, kerimisoffline commented on app/src/main/java/com/example/tastesip/ui/fragment/CocktailCategoryFragment.kt
> +                is Resource.Loading -> {
yuvarlak bir progress bar ekleyebiliriz. hatta öneri olarak lottie animasyon ekleyebilirsin yemekle ilgili. yükleme uzun sürerse kullanıcı beyaz ekranda beklemesin

2024-08-12 11:16 UTC, kerimisoffline commented on app/src/main/java/com/example/tastesip/ui/fragment/CocktailDetailFragment.kt
> +                        val ingredients = cocktailDetail.ingredientsAndMeasuresList
bu mapleme işleminin arayüzle bir ilgisi yok gibi. o yüzden live data'yı setlediğimiz yerde viewmodel'e taşıyabiliriz sanki. Buradaki yükü azaltır

2024-08-12 11:16 UTC, kerimisoffline commented on app/src/main/java/com/example/tastesip/ui/fragment/CocktailDetailFragment.kt
> +                        resource.message ?: "Bir hata oluştu",
hata mesajlarını string.xml'de toplayalım

2024-08-15 15:00 UTC, kerimisoffline approved these changes
Eline sağlık, güzel bir çalışma oldu.

2024-08-15 15:00 UTC, kerimisoffline commented on app/src/main/java/com/example/tastesip/ui/fragment/CategoryFragment.kt
> +    abstract fun setupRecyclerView()
Bu kullanım olmuş. Eğer her bu fonksiyon çağırıldığında bu class içerisinde bir işlem yapmak isteseydim. `open fun setupRecyclerView() {}` yapıp, çağırıldığı yerde `super.setupRecyclerView()` diyerek alt fragment'tan buranın içerisindeki kodu da tetikletebilirdim. Mesele tamamen neyi ortak kullanıp neyi ortak kullanamayacağım üzere. Dikkat ettiysen önce sistemi yazdın. Sonra benzer olduğunu görüp ortak bir fragment'a bağladın. Kullanılan methodlar ortaklaştıkça/ özelleştikçe de ona göre methodları düzenleyebiliriz.

2024-08-15 15:00 UTC, kerimisoffline commented on app/src/main/java/com/example/tastesip/ui/fragment/CategoryFragment.kt
> +abstract class CategoryFragment<T : Any> : Fragment() {
Burada Any kullanmak yerine yeni bir Category adında class oluşturup MealCategory ve CocktailCategory'leride ondan implement ederek aynı fragmentta yaptığımız gibi ortaklaştırabiliriz. O zaman Any yerine Category yazmam yeterli olur. Çoğu gerçek proje senaryosunda type olarak Any kullanmamaya özen gösteririz. Kullanılan durumlarda oluyor tabi. Bu düzeltmeyi yapmamıza şimdilik gerek yok. Bilgi olarak bıraktım.

abstract class Category (
     open val id
)

data class MealCategory(
override val id
) : Category()

2024-08-15 15:00 UTC, kerimisoffline commented on app/src/main/java/com/example/tastesip/ui/viewmodel/RecipeViewModelFactory.kt
> +package com.example.tastesip.ui.viewmodel
Factory classlarıyla viewmodel kurulumunu sadeleştirmenin yanında bir çok avantaj sağlayan, "Dependecy Injection" kütüphanemiz olan "Android Dagger Hilt" kullanabiliriz. Task-5'te bu bahsettiğim kütüphaneyi kullanmanı bekliyorum senden.

2024-08-19 07:20 UTC, TamerSarioglu approved these changes
Eline sağlık

2024-08-19 08:11 UTC, merged